### ISSUE TITLE
public/js/popper.min.js.map 404 ERROR

### ISSUE THREAD

**Issue by XanderCam** [theinnovs/wc-estimate-and-quote#1]
DevTools failed to load SourceMap: Could not load content for https://innotec.nu/wp-content/plugins/wc-estimate-and-quote/public/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Seems that the file: popper.min.js.map
is missing from the installation package.

Please advice.
I really need this plugin

**Comment by innovs** [comment]
Fixed in version 1.0.2
