### ISSUE TITLE
When attempting to change "Estimate Export Footer Text," in settings original example text doesn't switch.

### ISSUE THREAD

**Issue by mitchellcrazyeye** [theinnovs/wc-estimate-and-quote#3]
Attempting to change the footer text in settings, and it wouldn't change to anything I set it to. I'm certain it's meant to be able to change, but it would seem it doesn't want to. 
![image](https://user-images.githubusercontent.com/19811106/122166185-e0d0b300-ce3e-11eb-8876-241bacf3945f.png)

**Comment by innovs** [comment]
@mitchellcrazyeye ,
Resolved in V 1.0.2.3
